version: '3.2'

networks:
    fabcar_net:
        external: 
            name: $SWARM_NET

services:

    ca_org2:
        networks:
            fabcar_net:
                aliases:
                    - ca.org2.example.com
                    - ca_org2
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 2
            placement:
                constraints:
                    - node.hostname == $ORG2_HOSTNAME
        image: hyperledger/fabric-ca:latest
        hostname: ca.org2.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca_org2
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/8da84269bfc9d274a533d1c0504a86ae3eab0afe217669a4a07c3ea53172dd5c_sk
        ports:
            - "8054:7054"   
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/8da84269bfc9d274a533d1c0504a86ae3eab0afe217669a4a07c3ea53172dd5c_sk -b admin:adminpw -d'
        volumes:
            - /home/ravi/fabric-samples/hlfnet/crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

    couchdb0_org2:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 2
            placement:
                constraints:
                    - node.hostname == $ORG2_HOSTNAME
        image: hyperledger/fabric-couchdb:latest
        hostname: couchdb0_org2
        networks:
           - fabcar_net

    couchdb1_org2:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 2
            placement:
                constraints:
                    - node.hostname == $ORG2_HOSTNAME
        image: hyperledger/fabric-couchdb:latest
        hostname: couchdb1_org2
        networks:
           - fabcar_net
